"""Compare extracted structures across checkpoints, seeds and architectures.

* transition timing: when does each crystallisation measure rise relative to
  memorisation (train acc -> 1) and generalisation (test acc -> 1)?
* task-level equivalence of idiosyncratic algebras: adjusted Rand index
  between the hidden-site partitions of different runs, agreement of the
  induced operation tables, algebraic invariants, and an isomorphism test up
  to relabelling (generator propagation) for the final operation tables.
* an external reference (uses labels, reported separately): ARI to the
  partition by the true sum.
"""

from __future__ import annotations

import numpy as np


def adjusted_rand_index(a: np.ndarray, b: np.ndarray) -> float:
    a = np.asarray(a)
    b = np.asarray(b)
    _, ai = np.unique(a, return_inverse=True)
    _, bi = np.unique(b, return_inverse=True)
    n = len(a)
    M = np.zeros((ai.max() + 1, bi.max() + 1))
    np.add.at(M, (ai, bi), 1)
    comb = lambda x: x * (x - 1) / 2.0
    sum_ij = comb(M).sum()
    sum_a = comb(M.sum(axis=1)).sum()
    sum_b = comb(M.sum(axis=0)).sum()
    total = comb(n)
    expected = sum_a * sum_b / total if total else 0.0
    max_idx = 0.5 * (sum_a + sum_b)
    denom = max_idx - expected
    return float((sum_ij - expected) / denom) if denom else 1.0


def half_rise_step(steps, values, start_step=0):
    """First step >= start_step at which the series reaches the midpoint
    between its value at start and its maximum thereafter."""
    steps = np.asarray(steps)
    v = np.asarray(values, dtype=float)
    mask = steps >= start_step
    if mask.sum() < 2:
        return None
    s, v = steps[mask], v[mask]
    v0, vmax = v[0], np.nanmax(v)
    if not np.isfinite(vmax) or vmax - v0 < 0.1:
        return None
    thr = v0 + 0.5 * (vmax - v0)
    idx = int(np.argmax(v >= thr))
    return int(s[idx])


def first_step(steps, values, thr):
    for s, v in zip(steps, values):
        if v >= thr:
            return int(s)
    return None


def isomorphic_by_generator(t1: np.ndarray, t2: np.ndarray) -> dict:
    """Try to find a bijection phi with phi(t1[a,b]) = t2[phi a, phi b] by
    propagating from a single generator (sufficient for cyclic structures;
    reports failure otherwise).  Tables are (p, p) int arrays over 0..p-1."""
    p = t1.shape[0]
    def orbit(t, g):
        seen = [g]
        cur = g
        while True:
            cur = int(t[cur, g])
            if cur in seen:
                break
            seen.append(cur)
        return seen
    for g1 in range(p):
        o1 = orbit(t1, g1)
        if len(o1) < p:
            continue
        for g2 in range(p):
            o2 = orbit(t2, g2)
            if len(o2) < p:
                continue
            phi = np.empty(p, dtype=int)
            phi[o1] = o2
            if np.array_equal(phi[t1], t2[phi[:, None], phi[None, :]]):
                return {"isomorphic": True, "generator_pair": [g1, g2]}
        return {"isomorphic": False, "reason": "no generator of t1 maps compatibly"}
    return {"isomorphic": False, "reason": "t1 is not generated by a single element"}


def invariants(op: np.ndarray, n_triples: int = 20000, rng=None) -> dict:
    rng = rng or np.random.default_rng(0)
    p = op.shape[0]
    a, b, c = (rng.integers(0, p, n_triples) for _ in range(3))
    ar = np.arange(p)
    id_score = np.array([0.5 * (np.mean(op[e] == ar) + np.mean(op[:, e] == ar)) for e in range(p)])
    return {
        "associativity": float(np.mean(op[op[a, b], c] == op[a, op[b, c]])),
        "commutativity": float(np.mean(op == op.T)),
        "identity": float(id_score.max()),
        "latin": float(0.5 * (np.mean([len(set(op[i].tolist())) == p for i in range(p)])
                              + np.mean([len(set(op[:, j].tolist())) == p for j in range(p)]))),
        "n_outputs": int(len(np.unique(op))),
    }


METRICS = ["metastability", "discreteness", "closure", "polarization", "compression",
           "op.associativity", "op.commutativity", "op.latin", "crystallization"]


def _get(d: dict, key: str):
    for k in key.split("."):
        d = d[k]
    return d


def run_timing(run: dict) -> dict:
    """Transition timing for one run: ``run`` has ``log`` (train log) and
    ``metrics`` ({step: extracted dict})."""
    steps = sorted(run["metrics"].keys())
    tl = {r["step"]: r for r in run["log"]}
    train_acc = [tl[s]["train_acc"] for s in steps]
    test_acc = [tl[s]["test_acc"] for s in steps]
    t_mem = first_step(steps, train_acc, 0.99)
    t_gen = first_step(steps, test_acc, 0.9)
    t_gen_half = half_rise_step(steps, test_acc)
    out = {"t_mem": t_mem, "t_gen": t_gen, "t_gen_half": t_gen_half, "metrics": {}}
    for m in METRICS:
        vals = [_get(run["metrics"][s], m) for s in steps]
        hr = half_rise_step(steps, vals, start_step=t_mem or 0)
        plateau = [v for s, v in zip(steps, vals) if t_mem is not None and t_gen is not None and t_mem <= s < t_gen]
        after = [v for s, v in zip(steps, vals) if t_gen is not None and s >= t_gen]
        out["metrics"][m] = {
            "half_rise": hr,
            "lag_vs_gen": (hr - t_gen_half) if (hr is not None and t_gen_half is not None) else None,
            "plateau_mean": float(np.mean(plateau)) if plateau else None,
            "after_mean": float(np.mean(after)) if after else None,
            "final": float(vals[-1]),
        }
    return out


def cross_run(runs: dict[str, dict], reference: np.ndarray | None = None) -> dict:
    """Pairwise structure comparison at every common checkpoint and at the end."""
    names = sorted(runs)
    common = sorted(set.intersection(*(set(r["metrics"].keys()) for r in runs.values())))
    per_step = {}
    for s in common:
        parts = {n: np.array(runs[n]["metrics"][s]["partition"]) for n in names}
        ops = {n: np.array(runs[n]["metrics"][s]["op_table"]) for n in names}
        aris, agree = [], []
        for i in range(len(names)):
            for j in range(i + 1, len(names)):
                aris.append(adjusted_rand_index(parts[names[i]], parts[names[j]]))
                agree.append(float(np.mean(ops[names[i]] == ops[names[j]])))
        entry = {"mean_ari": float(np.mean(aris)) if aris else None,
                 "mean_op_agreement": float(np.mean(agree)) if agree else None}
        if reference is not None:
            entry["ari_to_reference"] = {n: adjusted_rand_index(parts[n], reference) for n in names}
        per_step[s] = entry
    final = {}
    for i in range(len(names)):
        for j in range(i + 1, len(names)):
            si, sj = max(runs[names[i]]["metrics"]), max(runs[names[j]]["metrics"])
            ti = np.array(runs[names[i]]["metrics"][si]["op_table"])
            tj = np.array(runs[names[j]]["metrics"][sj]["op_table"])
            final[f"{names[i]} vs {names[j]}"] = {
                "ari": adjusted_rand_index(runs[names[i]]["metrics"][si]["partition"],
                                           runs[names[j]]["metrics"][sj]["partition"]),
                "op_agreement": float(np.mean(ti == tj)),
                "isomorphism": isomorphic_by_generator(ti, tj),
            }
    return {"common_steps": common, "per_step": per_step, "final_pairs": final,
            "final_invariants": {n: invariants(np.array(runs[n]["metrics"][max(runs[n]["metrics"])]["op_table"]))
                                 for n in names}}
