"""Blind quotient extraction for a recurrent substrate.

Things are the substrate's hidden configurations after prefixes of actions.
Two configurations are equivalent when continuing from either with the same
sampled suffixes yields the same predicted observations (substitutability
across contexts; this is the Myhill-Nerode construction, done on behaviour
rather than on the world).  Clicks are (configuration, action-chunk);
their products are configurations at the same site, so recursion is
automatic.  What is measured:

* behavioural classes of prefix configurations, discreteness, metastability
  under noise (as in ``extract.py``);
* closure: does the product of (class, action) land in a stable class;
* action coherence: is the induced action on classes well defined and
  compatible with concatenation ((c.a).b == c.(ab)) -- automatic for a
  deterministic sequential substrate *if* classes are well defined, so this
  is a check on the quotient, not a discovery;
* the induced automaton on classes, canonically labelled from the initial
  configuration, and the algebra it generates: are actions bijections, is
  the generated transformation monoid a group, its order, is it abelian.

Nothing about the world's state space, its group, or the labels is used.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import product

import numpy as np
import torch
import torch.nn.functional as F

from .extract import _js, leader_cluster


@dataclass
class SeqExtractConfig:
    prefix_len: int = 4  # all prefixes up to this length ...
    n_long_prefixes: int = 256  # ... plus random longer ones
    long_len: int = 10
    n_suffixes: int = 24
    suffix_len: int = 5
    eps_beh: float = 0.05
    d_far: float = 0.5
    sigmas: tuple = (0.25, 0.5, 1.0, 2.0)
    sigma_ref: float = 0.5
    n_noise: int = 4
    n_pair_sample: int = 300
    monoid_cap: int = 5000


def _all_prefixes(k: int, L: int):
    out = [()]
    for l in range(1, L + 1):
        out.extend(product(range(k), repeat=l))
    return out


def _states_after(model, prefixes, k):
    """Hidden configuration after each prefix (grouped by length)."""
    d = model.d
    H = torch.empty(len(prefixes), d)
    by_len = {}
    for i, p in enumerate(prefixes):
        by_len.setdefault(len(p), []).append(i)
    with torch.no_grad():
        for l, idx in by_len.items():
            if l == 0:
                H[idx] = model.initial().expand(len(idx), -1)
                continue
            A = torch.tensor([prefixes[i] for i in idx], dtype=torch.long)
            _, sites = model(A)
            H[idx] = sites["hidden"][:, -1]
    return H


def _behaviour(model, H, suffixes):
    """(n, d) configurations x (S, Ls) suffixes -> (n, S*Ls, n_obs) predicted observation distributions."""
    n = H.shape[0]
    S, Ls = suffixes.shape
    feats = []
    with torch.no_grad():
        for s in range(S):
            A = suffixes[s][None].expand(n, -1)
            lg, _ = model(A, h0=H)
            feats.append(F.softmax(lg, -1))  # (n, Ls, n_obs)
    return torch.cat(feats, dim=1).numpy()  # (n, S*Ls, n_obs)


def _classify(Bnew, leaders, eps):
    """Assign behaviours (m, C, o) to leaders (k, C, o); -1 if none within eps."""
    out = np.full(Bnew.shape[0], -1, dtype=int)
    for i in range(Bnew.shape[0]):
        d = _js(leaders, Bnew[i][None]).mean(axis=1)
        j = int(np.argmin(d))
        if d[j] < eps:
            out[i] = j
    return out


def canonical_automaton(T: np.ndarray, start: int) -> tuple[np.ndarray, list]:
    """BFS relabelling of the part reachable from ``start`` (-1 = undefined)."""
    k = T.shape[1]
    order = [start]
    pos = {start: 0}
    i = 0
    while i < len(order):
        c = order[i]; i += 1
        for a in range(k):
            t = int(T[c, a])
            if t >= 0 and t not in pos:
                pos[t] = len(order); order.append(t)
    m = len(order)
    C = np.full((m, k), -1, dtype=int)
    for c in order:
        for a in range(k):
            t = int(T[c, a])
            C[pos[c], a] = pos[t] if t in pos else -1
    return C, order


def monoid_analysis(C: np.ndarray, cap: int) -> dict:
    """The transformation monoid generated by the action maps on the
    reachable classes (only meaningful when the table is total)."""
    m, k = C.shape
    if (C < 0).any():
        return {"total": False}
    gens = [tuple(C[:, a].tolist()) for a in range(k)]
    ident = tuple(range(m))
    seen = {ident}
    frontier = [ident]
    while frontier and len(seen) < cap:
        f = frontier.pop()
        for g in gens:
            h = tuple(g[x] for x in f)  # apply f then g
            if h not in seen:
                seen.add(h); frontier.append(h)
    bij = [len(set(g)) == m for g in gens]
    all_bij = all(len(set(e)) == m for e in seen)
    commute = all(tuple(g2[x] for x in g1) == tuple(g1[x] for x in g2) for g1 in gens for g2 in gens)
    return {"total": True, "actions_bijective": bij, "monoid_order": len(seen),
            "capped": len(seen) >= cap, "is_group": all_bij, "abelian": commute}


def extract_seq(model, n_actions: int, cfg: SeqExtractConfig, rng: np.random.Generator) -> dict:
    model.eval()
    k = n_actions
    prefixes = _all_prefixes(k, cfg.prefix_len)
    long = [tuple(rng.integers(0, k, cfg.long_len)) for _ in range(cfg.n_long_prefixes)]
    prefixes = prefixes + long
    n = len(prefixes)
    H = _states_after(model, prefixes, k)
    suffixes = torch.tensor(rng.integers(0, k, (cfg.n_suffixes, cfg.suffix_len)), dtype=torch.long)
    B = _behaviour(model, H, suffixes)  # (n, C, o)
    n_ctx = B.shape[1]
    labels, leaders = leader_cluster(B.reshape(n, -1), n_ctx, cfg.eps_beh)
    n_classes = int(labels.max()) + 1
    class_size = np.bincount(labels)
    # representative configuration of each class: the first prefix in it
    rep_idx = np.array([int(np.argmax(labels == c)) for c in range(n_classes)])
    Hrep = H[rep_idx]

    # discreteness
    m = min(cfg.n_pair_sample, n)
    sub = rng.choice(n, size=m, replace=False)
    Bs = B[sub]
    d = np.concatenate([_js(Bs[i + 1:], Bs[i][None]).mean(axis=1) for i in range(m - 1)])
    discreteness = float(np.mean(d < cfg.eps_beh) + np.mean(d > cfg.d_far))

    # metastability: retention of class under noise on the configuration
    retention = {}
    ret_ref = np.zeros(n)
    for sigma in cfg.sigmas:
        keep = np.zeros(n)
        for _ in range(cfg.n_noise):
            with torch.no_grad():
                rms = H.pow(2).mean(dim=-1, keepdim=True).sqrt().mean()
                Hn = H + float(sigma) * rms * torch.randn_like(H)
            Bn = _behaviour(model, Hn, suffixes)
            keep += (_js(Bn, B).mean(axis=1) < cfg.eps_beh)
        keep /= cfg.n_noise
        retention[sigma] = float(keep.mean())
        if sigma == cfg.sigma_ref:
            ret_ref = keep
    metastability = float(np.mean(list(retention.values())))
    class_ret = np.zeros(n_classes)
    np.add.at(class_ret, labels, ret_ref)
    class_ret /= np.maximum(class_size, 1)

    # clicks: (class, action) -> class ; closure = stability of the product's class
    T = np.full((n_classes, k), -1, dtype=int)
    prod_ret = []
    with torch.no_grad():
        for a in range(k):
            A = torch.full((n_classes, 1), a, dtype=torch.long)
            _, sites = model(A, h0=Hrep)
            Hp = sites["hidden"][:, -1]
            Bp = _behaviour(model, Hp, suffixes)
            T[:, a] = _classify(Bp, leaders, cfg.eps_beh)
    known = T >= 0
    closure = float(np.mean(np.where(known, class_ret[np.maximum(T, 0)], 0.0)))
    # arity 3: (class, a, b) -> class consistent with (class.a).b ?
    n_chk = n_coh = 0
    with torch.no_grad():
        pairs = [(a, b) for a in range(k) for b in range(k)]
        for a, b in pairs:
            A = torch.tensor([[a, b]] * n_classes, dtype=torch.long)
            _, sites = model(A, h0=Hrep)
            Bp = _behaviour(model, sites["hidden"][:, -1], suffixes)
            direct = _classify(Bp, leaders, cfg.eps_beh)
            via = np.where(T[:, a] >= 0, T[np.maximum(T[:, a], 0), b], -1)
            ok = (direct >= 0) & (via >= 0)
            n_chk += int(ok.sum()); n_coh += int((direct[ok] == via[ok]).sum())
    coherence = (n_coh / n_chk) if n_chk else 0.0

    start = int(labels[0])  # class of the empty prefix
    C, order = canonical_automaton(T, start)
    mon = monoid_analysis(C, cfg.monoid_cap)
    nondegenerate = float(1.0 - class_size.max() / n)
    lawfree = float((max(metastability, 1e-9) * max(closure, 1e-9)) ** 0.5 * nondegenerate)
    return {
        "n_prefixes": n,
        "n_classes": n_classes,
        "n_reachable_classes": int(C.shape[0]),
        "compression": float(1.0 - n_classes / n),
        "discreteness": discreteness,
        "retention": {str(s): v for s, v in retention.items()},
        "metastability": metastability,
        "closure": closure,
        "frac_products_known": float(known.mean()),
        "action_coherence": coherence,
        "nondegenerate": nondegenerate,
        "crystallization_lawfree": lawfree,
        "monoid": mon,
        "canonical_table": C.tolist(),
        "partition": labels.tolist(),
    }
