/-!
# Emergent types as quotients by interaction-indistinguishability

The Python side of this repository discovers, empirically, a finite set of
metastable basins and a *partial* click operation between them.  This file
formalises the algebra that such a finite structure induces, independently of
how it was discovered.

Nothing here simulates dynamics.  The substrate enters only through the
abstract type `B` of basins and the partial operation `click : B → B → Option B`.

Main results:

* `BehEq` (interaction-indistinguishability) is an equivalence relation, so
  `EmergentType S := Quotient S.behEqSetoid` is well defined:
  **Type = Basin / interaction-indistinguishability**.
* If clicking respects behavioural equivalence (`Respects`), it descends to a
  well-defined partial operation on emergent types (`EmergentType.click`),
  with `click ⟦a⟧ ⟦b⟧ = (S.click a b).map ⟦·⟧`.
* If clicking is moreover associative *up to behavioural equivalence* on the
  substrate (`AssocUpToBehEq`), the descended operation is associative
  *exactly* (`EmergentType.click_assoc`): approximate physical sameness
  becomes mathematical equality after quotienting.

All hypotheses are stated with explicit binders over `B` so that, for a finite
`B` with decidable equality, they can be checked by `decide` on a concrete
exported table (see `Emergence/Discovered.lean`, generated by `emergence/export.py`).
-/

universe u

namespace Emergence

/-- An interaction structure: a partial binary click operation on things. -/
structure Interaction (B : Type u) where
  click : B → B → Option B

namespace Interaction

variable {B : Type u} (S : Interaction B)

/-- `a` and `b` fit together: their click is defined. -/
def Compatible (a b : B) : Prop := (S.click a b).isSome = true

instance (a b : B) : Decidable (S.Compatible a b) := inferInstanceAs (Decidable (_ = true))

/-- Interaction-indistinguishability: no partner tells `a` and `b` apart, on
either side. -/
def BehEq (a b : B) : Prop :=
  ∀ c, (S.Compatible a c ↔ S.Compatible b c) ∧ (S.Compatible c a ↔ S.Compatible c b)

theorem BehEq.refl (a : B) : S.BehEq a a := fun _ => ⟨Iff.rfl, Iff.rfl⟩

theorem BehEq.symm {a b : B} (h : S.BehEq a b) : S.BehEq b a :=
  fun c => ⟨(h c).1.symm, (h c).2.symm⟩

theorem BehEq.trans {a b c : B} (h₁ : S.BehEq a b) (h₂ : S.BehEq b c) : S.BehEq a c :=
  fun d => ⟨(h₁ d).1.trans (h₂ d).1, (h₁ d).2.trans (h₂ d).2⟩

theorem BehEq.equivalence : Equivalence S.BehEq :=
  ⟨BehEq.refl S, fun h => BehEq.symm S h, fun h₁ h₂ => BehEq.trans S h₁ h₂⟩

/-- The setoid of behavioural equivalence. -/
def behEqSetoid : Setoid B := ⟨S.BehEq, BehEq.equivalence S⟩

/-- **Emergent types**: basins modulo interaction-indistinguishability. -/
def EmergentType : Type u := Quotient S.behEqSetoid

/-- The type of a thing. -/
def typeOf (a : B) : S.EmergentType := Quotient.mk S.behEqSetoid a

theorem typeOf_eq_iff {a b : B} : S.typeOf a = S.typeOf b ↔ S.BehEq a b :=
  ⟨fun h => Quotient.exact h, fun h => Quotient.sound h⟩

/-- Behavioural equivalence of *possible* results: undefined matches undefined,
defined matches defined up to `BehEq`. -/
def OptBehEq : Option B → Option B → Prop
  | none, none => True
  | some d, some d' => S.BehEq d d'
  | _, _ => False

theorem OptBehEq.refl (o : Option B) : S.OptBehEq o o := by
  cases o <;> simp [OptBehEq, BehEq.refl]

theorem OptBehEq.symm {o o' : Option B} (h : S.OptBehEq o o') : S.OptBehEq o' o := by
  cases o <;> cases o' <;> simp_all [OptBehEq, BehEq.symm]

theorem OptBehEq.trans {o₁ o₂ o₃ : Option B} (h₁ : S.OptBehEq o₁ o₂) (h₂ : S.OptBehEq o₂ o₃) :
    S.OptBehEq o₁ o₃ := by
  cases o₁ <;> cases o₂ <;> cases o₃ <;> simp_all [OptBehEq]
  exact BehEq.trans S h₁ h₂

/-- The key bridge: results that are behaviourally equivalent are *equal* once
mapped into the quotient. -/
theorem OptBehEq.map_typeOf_eq {o o' : Option B} (h : S.OptBehEq o o') :
    o.map S.typeOf = o'.map S.typeOf := by
  cases o <;> cases o' <;> simp_all [OptBehEq, Option.map]
  exact Quotient.sound h

/-- Hypothesis (measured by `emergence/compose.py::substitutability`): clicking
respects behavioural equivalence in each argument. -/
structure Respects : Prop where
  left : ∀ a a' b, S.BehEq a a' → S.OptBehEq (S.click a b) (S.click a' b)
  right : ∀ a b b', S.BehEq b b' → S.OptBehEq (S.click a b) (S.click a b')

theorem Respects.both (h : S.Respects) {a a' b b' : B} (ha : S.BehEq a a') (hb : S.BehEq b b') :
    S.OptBehEq (S.click a b) (S.click a' b') :=
  OptBehEq.trans S (h.left a a' b ha) (h.right a' b b' hb)

/-- Clicking lifted to results in the quotient. -/
def liftClick (a b : B) : Option S.EmergentType := (S.click a b).map S.typeOf

theorem liftClick_respects (h : S.Respects) {a a' b b' : B} (ha : S.BehEq a a') (hb : S.BehEq b b') :
    S.liftClick a b = S.liftClick a' b' :=
  OptBehEq.map_typeOf_eq S (Respects.both S h ha hb)

/-- **Descent**: a click that respects behavioural equivalence is a well-defined
partial operation on emergent types. -/
def EmergentType.click (h : S.Respects) : S.EmergentType → S.EmergentType → Option S.EmergentType :=
  Quotient.lift₂ S.liftClick (fun _ _ _ _ ha hb => S.liftClick_respects h ha hb)

@[simp] theorem EmergentType.click_typeOf (h : S.Respects) (a b : B) :
    EmergentType.click S h (S.typeOf a) (S.typeOf b) = (S.click a b).map S.typeOf := rfl

/-- `(a * b) * c` on the substrate. -/
def clickL (a b c : B) : Option B := (S.click a b).bind fun d => S.click d c

/-- `a * (b * c)` on the substrate. -/
def clickR (a b c : B) : Option B := (S.click b c).bind fun d => S.click a d

/-- Strong hypothesis: clicking is associative up to behavioural equivalence,
*including definedness* (`(a*b)*c` defined iff `a*(b*c)` defined).  This is
what a category or partial monoid would satisfy; a commutative "chemical"
click typically does not (A*B and (A*B)*C can be defined while B*C is not). -/
def AssocUpToBehEq : Prop := ∀ a b c, S.OptBehEq (S.clickL a b c) (S.clickR a b c)

/-- Results agree when both are defined; no constraint otherwise. -/
def OptWeakEq : Option B → Option B → Prop
  | some d, some d' => S.BehEq d d'
  | _, _ => True

/-- Weak hypothesis (measured by `emergence/compose.py::associativity`): whenever
both bracketings are defined, their results are behaviourally equivalent. -/
def WeakAssocUpToBehEq : Prop := ∀ a b c, S.OptWeakEq (S.clickL a b c) (S.clickR a b c)

theorem AssocUpToBehEq.weak (h : S.AssocUpToBehEq) : S.WeakAssocUpToBehEq := by
  intro a b c
  have := h a b c
  revert this
  cases S.clickL a b c <;> cases S.clickR a b c <;> simp [OptBehEq, OptWeakEq]

theorem bind_map_typeOf (h : S.Respects) (o : Option B) (c : B) :
    (o.map S.typeOf).bind (fun w => EmergentType.click S h w (S.typeOf c)) =
      (o.bind fun d => S.click d c).map S.typeOf := by
  cases o <;> rfl

theorem map_typeOf_bind (h : S.Respects) (a : B) (o : Option B) :
    (o.map S.typeOf).bind (fun w => EmergentType.click S h (S.typeOf a) w) =
      (o.bind fun d => S.click a d).map S.typeOf := by
  cases o <;> rfl

/-- **Exactness**: associativity up to behavioural equivalence on the substrate
descends to exact associativity on emergent types. -/
theorem EmergentType.click_assoc (h : S.Respects) (ha : S.AssocUpToBehEq)
    (x y z : S.EmergentType) :
    (EmergentType.click S h x y).bind (fun w => EmergentType.click S h w z) =
      (EmergentType.click S h y z).bind (fun w => EmergentType.click S h x w) := by
  induction x using Quotient.inductionOn with | _ a =>
  induction y using Quotient.inductionOn with | _ b =>
  induction z using Quotient.inductionOn with | _ c =>
  show (S.liftClick a b).bind (fun w => EmergentType.click S h w (S.typeOf c)) =
      (S.liftClick b c).bind (fun w => EmergentType.click S h (S.typeOf a) w)
  unfold liftClick
  rw [S.bind_map_typeOf h, S.map_typeOf_bind h]
  exact OptBehEq.map_typeOf_eq S (ha a b c)

/-- **Exactness (weak form)**: if both bracketings are defined on emergent
types, they are equal.  Only weak associativity on the substrate is needed. -/
theorem EmergentType.click_assoc_of_some (h : S.Respects) (ha : S.WeakAssocUpToBehEq)
    (x y z : S.EmergentType) {w w' : S.EmergentType}
    (hl : (EmergentType.click S h x y).bind (fun v => EmergentType.click S h v z) = some w)
    (hr : (EmergentType.click S h y z).bind (fun v => EmergentType.click S h x v) = some w') :
    w = w' := by
  induction x using Quotient.inductionOn with | _ a =>
  induction y using Quotient.inductionOn with | _ b =>
  induction z using Quotient.inductionOn with | _ c =>
  change (S.liftClick a b).bind (fun v => EmergentType.click S h v (S.typeOf c)) = some w at hl
  change (S.liftClick b c).bind (fun v => EmergentType.click S h (S.typeOf a) v) = some w' at hr
  unfold liftClick at hl hr
  rw [S.bind_map_typeOf h] at hl
  rw [S.map_typeOf_bind h] at hr
  change (S.clickL a b c).map S.typeOf = some w at hl
  change (S.clickR a b c).map S.typeOf = some w' at hr
  have key := ha a b c
  revert hl hr key
  cases S.clickL a b c with
  | none => intro hl; simp at hl
  | some d =>
    cases S.clickR a b c with
    | none => intro _ hr; simp at hr
    | some d' =>
      intro hl hr key
      simp only [Option.map, Option.some.injEq] at hl hr
      subst hl; subst hr
      exact Quotient.sound key

end Interaction

end Emergence
