import Emergence.Finite

/-!
# Discovered interaction structure (generated by `emergence/export.py`)

`14` metastable basins; a `some j` entry at `(i, j')` means the click of
`i` with `j'` was defined (C >= c_thresh) and its product landed in basin `j`.
Names and Python type labels are comments only: Lean recomputes behavioural
equivalence from the table itself.
-/

namespace Emergence.Discovered

open Interaction Finite

def discovered : Interaction (Fin 14) :=
  ofTable 14 [
    -- 0: Q (type 0)
    [none, none, none, none, none, none, none, none, none, none, none, none, none, none],
    -- 1: J (type 0)
    [none, none, none, none, none, none, none, none, none, none, none, none, none, none],
    -- 2: P (type 0)
    [none, none, none, none, none, none, none, none, none, none, none, none, none, none],
    -- 3: A1 (type 1)
    [none, none, none, none, none, none, none, some 8, none, none, some 12, none, none, none],
    -- 4: C (type 2)
    [none, none, none, none, none, none, none, some 10, some 12, some 11, none, none, none, none],
    -- 5: A2 (type 1)
    [none, none, none, none, none, none, none, some 9, none, none, some 11, none, none, none],
    -- 6: R (type 0)
    [none, none, none, none, none, none, none, none, none, none, none, none, none, none],
    -- 7: B (type 3)
    [none, none, none, some 8, some 10, some 9, none, none, none, none, none, none, none, none],
    -- 8: D1 (type 4)
    [none, none, none, none, some 12, none, none, none, none, none, none, none, none, none],
    -- 9: D2 (type 4)
    [none, none, none, none, some 11, none, none, none, none, none, none, none, none, none],
    -- 10: Dp (type 5)
    [none, none, none, some 12, none, some 11, none, none, none, none, none, none, none, none],
    -- 11: E2 (type 0)
    [none, none, none, none, none, none, none, none, none, none, none, none, none, none],
    -- 12: E1 (type 0)
    [none, none, none, none, none, none, none, none, none, none, none, none, none, none],
    -- 13: S (type 0)
    [none, none, none, none, none, none, none, none, none, none, none, none, none, none]]

example : discovered.BehEq 0 1 := by decide  -- Q ~ J
example : discovered.BehEq 0 2 := by decide  -- Q ~ P
example : discovered.BehEq 0 6 := by decide  -- Q ~ R
example : discovered.BehEq 0 11 := by decide  -- Q ~ E2
example : discovered.BehEq 0 12 := by decide  -- Q ~ E1
example : discovered.BehEq 0 13 := by decide  -- Q ~ S
example : discovered.BehEq 1 2 := by decide  -- J ~ P
example : discovered.BehEq 1 6 := by decide  -- J ~ R
example : discovered.BehEq 1 11 := by decide  -- J ~ E2
example : discovered.BehEq 1 12 := by decide  -- J ~ E1
example : discovered.BehEq 1 13 := by decide  -- J ~ S
example : discovered.BehEq 2 6 := by decide  -- P ~ R

/-- Clicking respects behavioural equivalence (`emergence/compose.py::substitutability`). -/
theorem discovered_respects : discovered.Respects := by
  constructor <;> decide

/-- Whenever both bracketings are defined their results are behaviourally equal
(`emergence/compose.py::associativity`). -/
theorem discovered_weak_assoc : discovered.WeakAssocUpToBehEq := by decide

/-- The emergent types therefore carry a partial operation that is exactly
associative wherever both sides are defined. -/
theorem discovered_types_assoc (x y z : discovered.EmergentType) {w w' : discovered.EmergentType}
    (hl : (EmergentType.click discovered discovered_respects x y).bind
        (fun v => EmergentType.click discovered discovered_respects v z) = some w)
    (hr : (EmergentType.click discovered discovered_respects y z).bind
        (fun v => EmergentType.click discovered discovered_respects x v) = some w') :
    w = w' :=
  EmergentType.click_assoc_of_some discovered discovered_respects discovered_weak_assoc x y z hl hr

end Emergence.Discovered
