"""Export a discovered finite click structure to Lean.

The generated file builds the structure with `Interaction.ofTable` and states
the two hypotheses of `Emergence/Basic.lean` as theorems proved by `decide`.
If the discovered structure violates one of them, `lake build` fails on that
theorem: the Lean file is the certificate that the empirically discovered
partial algebra descends to an exact one on emergent types.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np


def export_lean(table, types: np.ndarray, names: list[str], path: Path, module: str = "Discovered") -> Path:
    k = table.k
    rows = []
    for i in range(k):
        cells = []
        for j in range(k):
            p = int(table.product[i, j])
            cells.append(f"some {p}" if p >= 0 else "none")
        comment = f"-- {i}: {names[i]} (type {int(types[i])})"
        rows.append(f"    {comment}\n    [{', '.join(cells)}]")
    body = ",\n".join(rows)
    # pairs of basins that are exactly behaviourally equivalent in the table
    from .compose import exact_types

    ex = exact_types(table)
    same = [(i, j) for i in range(k) for j in range(i + 1, k) if ex[i] == ex[j]]
    same_examples = "\n".join(
        f"example : discovered.BehEq {i} {j} := by decide  -- {names[i]} ~ {names[j]}" for i, j in same[:12]
    )
    if not same:
        same_examples = "-- no two basins are exactly behaviourally equivalent in this table"
    text = f"""import Emergence.Finite

/-!
# Discovered interaction structure (generated by `emergence/export.py`)

`{k}` metastable basins; a `some j` entry at `(i, j')` means the click of
`i` with `j'` was defined (C >= c_thresh) and its product landed in basin `j`.
Names and Python type labels are comments only: Lean recomputes behavioural
equivalence from the table itself.
-/

namespace Emergence.Discovered

open Interaction Finite

def discovered : Interaction (Fin {k}) :=
  ofTable {k} [
{body}]

{same_examples}

/-- Clicking respects behavioural equivalence (`emergence/compose.py::substitutability`). -/
theorem discovered_respects : discovered.Respects := by
  constructor <;> decide

/-- Whenever both bracketings are defined their results are behaviourally equal
(`emergence/compose.py::associativity`). -/
theorem discovered_weak_assoc : discovered.WeakAssocUpToBehEq := by decide

/-- The emergent types therefore carry a partial operation that is exactly
associative wherever both sides are defined. -/
theorem discovered_types_assoc (x y z : discovered.EmergentType) {{w w' : discovered.EmergentType}}
    (hl : (EmergentType.click discovered discovered_respects x y).bind
        (fun v => EmergentType.click discovered discovered_respects v z) = some w)
    (hr : (EmergentType.click discovered discovered_respects y z).bind
        (fun v => EmergentType.click discovered discovered_respects x v) = some w') :
    w = w' :=
  EmergentType.click_assoc_of_some discovered discovered_respects discovered_weak_assoc x y z hl hr

end Emergence.Discovered
"""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    return path
