import Emergence.Basic
import Emergence.Finite
import Emergence.Multi
import Emergence.Equiv
-- `Emergence.Discovered` is generated by `emergence/export.py` and built
-- explicitly with `lake build Emergence.Discovered`; it is the certificate
-- for one discovered finite structure and is not part of the library root.
